apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-topology-anti-pod-prefer
  name: demo-topology-anti-pod-prefer
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo-topology-anti-pod-prefer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-topology-anti-pod-prefer
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - demo-topology-anti-pod-prefer
              topologyKey: kubernetes.io/hostname
      containers:
      - image: quay.io/rh_ee_swongpai/py-http-call:52f987b597c5e2425cad791d32060cbdf8091150
        name: py-http-call
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        resources: {}
